when:
  event: [tag]
  branch: master

steps:
  - name: build & publish
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: git.gamecrash.dev/game.crash/verteiler
      registry:
        from_secret: reg_url
      username:
        from_secret: reg_owner
      password:
        from_secret: reg_token
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
      tags:
        - ${CI_COMMIT_TAG}
        - ${CI_COMMIT_TAG:0:3}
        - ${CI_COMMIT_TAG:0:1}
      compress: true

